# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 375)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_main = QtWidgets.QWidget(Dialog)
        self.widget_main.setStyleSheet("QWidget#widget_main{background:qlineargradient(spread:pad,x1:0,y1:0,x2:1,y2:0,stop:0 #4568dc,stop:1 #b06ab3);border-top-left-radius:2px;border-top-right-radius:2px;}")
        self.widget_main.setObjectName("widget_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_main)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane{border-width:1px;border-style:solid;border-color:rgba(255,255,255,0.7);background:transparent;}\n"
"QTabWidget::tab-bar{background:transparent;subcontrol-position:left;}\n"
"QTabBar::tab{min-width:70px;min-height:20px;background:transparent;}\n"
"QTabBar::tab:selected{color: rgb(255,255,255);background-color:rgba(165,106,183,0.8);}\n"
"QTabBar::tab:!selected{color: blank;background:transparent;}\n"
"QTabBar::tab:hover{color: rgb(255,255,255);background-color:rgba(165,106,183,0.8);}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        self.radioButton_z = QtWidgets.QRadioButton(self.widget)
        self.radioButton_z.setObjectName("radioButton_z")
        self.gridLayout_2.addWidget(self.radioButton_z, 2, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_z = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.comboBox_z.setFont(font)
        self.comboBox_z.setObjectName("comboBox_z")
        self.gridLayout_2.addWidget(self.comboBox_z, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 7)
        self.label_pic = QtWidgets.QLabel(self.widget)
        self.label_pic.setMinimumSize(QtCore.QSize(100, 100))
        self.label_pic.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        self.label_pic.setFont(font)
        self.label_pic.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_pic.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pic.setObjectName("label_pic")
        self.gridLayout_2.addWidget(self.label_pic, 4, 6, 1, 1)
        self.comboBox_d = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.comboBox_d.setFont(font)
        self.comboBox_d.setObjectName("comboBox_d")
        self.gridLayout_2.addWidget(self.comboBox_d, 1, 1, 1, 6)
        self.lineEdit_choose = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_choose.setObjectName("lineEdit_choose")
        self.gridLayout_2.addWidget(self.lineEdit_choose, 3, 1, 1, 2)
        self.pushButton_choose = QtWidgets.QPushButton(self.widget)
        self.pushButton_choose.setObjectName("pushButton_choose")
        self.gridLayout_2.addWidget(self.pushButton_choose, 3, 6, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.widget_2 = QtWidgets.QWidget(self.widget_main)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(253, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_yes = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.horizontalLayout.addWidget(self.pushButton_yes)
        self.pushButton_no = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_no.setObjectName("pushButton_no")
        self.horizontalLayout.addWidget(self.pushButton_no)
        self.pushButton_set = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_set.setObjectName("pushButton_set")
        self.horizontalLayout.addWidget(self.pushButton_set)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget_main)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton_z.setText(_translate("Dialog", "自定义"))
        self.label_3.setText(_translate("Dialog", "助手精灵："))
        self.label.setText(_translate("Dialog", "配色方案："))
        self.label_2.setText(_translate("Dialog", "本界面的背景色以及图片均为演示效果，点击应用后可改变主界面效果"))
        self.label_pic.setText(_translate("Dialog", "演示图"))
        self.pushButton_choose.setText(_translate("Dialog", "选择图片"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "界面设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "系统设置"))
        self.pushButton_yes.setText(_translate("Dialog", "确认"))
        self.pushButton_no.setText(_translate("Dialog", "取消"))
        self.pushButton_set.setText(_translate("Dialog", "应用"))
